		
		<?php
			$form = $this->form;
			$mode == 'edit' ? $mode = 'edit' : $mode = 'create';
			$form->setAttributes(array(
				'action' => $this->url('cticket/ticket-admin', array ('action' => $mode)),
				'method' => 'POST',
			));
		
			$form->prepare();
			echo $this->form()->openTag($form);
		?>
			<?php echo $this->formHidden($form->get('id')); ?>
			<?php echo $this->formHidden($form->get('security')); ?>
			<?php echo $this->formHidden($form->get('status')->setValue(1)); ?>
			
			
			
		<div class="row">
		<div class="col-md-6">
			<?php echo $this->formLabel($form->get('subject')); ?>
			<?php echo $this->formElementErrors($form->get('subject')); ?>
			<?php
			echo $this->formElement($form->get('subject')
					->setAttributes(array(
						'class' => 'form-control',
						'placeholder' => ''
				)));
			?>
		
			<?php echo $this->formLabel($form->get('body')); ?>
			<?php echo $this->formElementErrors($form->get('body')); ?>
			<?php
			echo $this->formElement($form->get('body')
					->setAttributes(array(
						'class' => 'form-control',
						'placeholder' => ''
				)));
			?>
			
			<?php echo $this->formLabel($form->get('priority')) ?>
			<?php echo $this->formElement($form->get('priority')->setAttribute('class' , 'form-control dropdown')) ?>
		</div>
		<div class="col-md-6">
			
			<?php echo $this->formLabel($form->get('category')) ?>
			<?php echo $this->formElement($form->get('category')->setAttribute('class' , 'form-control dropdown')) ?>
			
			<?php echo $this->formLabel($form->get('contact')) ?>
			<?php echo $this->formElementErrors($form->get('contact')); ?>
			<?php echo $this->formElement($form->get('contact')->setAttribute('class' , 'form-control')) ?>
			
			<?php echo $this->formLabel($form->get('email')) ?>
			<?php echo $this->formElementErrors($form->get('email')); ?>
			<?php echo $this->formElement($form->get('email')->setAttribute('class' , 'form-control')) ?>
			
			
			<?php
				echo $this->formElement($form->get('submit')
						->setAttributes(array(
							'class' => 'btn btn-lg btn-primary',
							'value' => $mode,
					)));
		
			?>
			<?php echo $this->form()->closeTag(); ?>
		</div>
		
		</div>
