 <div class="page-header">
 	<h2><?php echo $this->translate('New Ticket'); ?></h2>
 </div>
<div class="row">
	<ol class="breadcrumb">
	  <li><a href="<?php echo $this->url('home') ?>"><?php echo $this->translate('Home') ?></a></li>
	  <li><a href="<?php echo $this->url('cticket/ticket-admin') ?>"><?php echo $this->translate('List') ?></a></li>
	  <li class="active"><?php echo $this->translate('New Ticket') ?></li>
	</ol>
</div>
<div class="row">
	<?php 
	if($error!=null) {
	echo '<div class="alert alert-warning">';
		print_r($error);
	echo '</div>';
	}
	?>
</div>
<div class="row">
	<div class="continer">
		<div class="panel panel-default ">
			<div class="panel-heading"><?php echo $this->translate('Ticket Details'); ?></div>
			<div class="panel-body">
			<?php
				$form = $this->form;
				$form->setAttributes(array(
					'action' => $this->url('cticket/ticket-admin', array ('action' => 'create')),
					'method' => 'POST',
				));
			
				$form->prepare();
				echo $this->form()->openTag($form);
			?>
				<?php echo $this->formHidden($form->get('id')); ?>
				<?php echo $this->formHidden($form->get('security')); ?>
				<?php echo $this->formHidden($form->get('status')->setValue(1)); ?>
				
				
				
			<div class="row">
			<div class="col-md-6">
				<?php echo $this->formLabel($form->get('subject')); ?>
				<?php echo $this->formElementErrors($form->get('subject')); ?>
				<?php
				echo $this->formElement($form->get('subject')
						->setAttributes(array(
							'class' => 'form-control',
							'placeholder' => ''
					)));
				?>
			
				<?php echo $this->formLabel($form->get('body')); ?>
				<?php echo $this->formElementErrors($form->get('body')); ?>
				<?php
				echo $this->formElement($form->get('body')
						->setAttributes(array(
							'class' => 'form-control',
							'rows' => '6'
					)));
				?>
			</div>
			<div class="container col-md-6">
				<?php echo $this->formLabel($form->get('priority')) ?>
				<?php echo $this->formElement($form->get('priority')->setAttribute('class' , 'form-control dropdown')) ?>
				<?php echo $this->formLabel($form->get('category')) ?>
				<?php echo $this->formElement($form->get('category')->setAttribute('class' , 'form-control dropdown')) ?>
				
				<?php echo $this->formLabel($form->get('contact')) ?>
				<?php echo $this->formElementErrors($form->get('contact')); ?>
				<?php echo $this->formElement($form->get('contact')->setAttribute('class' , 'form-control')) ?>
				
				<?php echo $this->formLabel($form->get('email')) ?>
				<?php echo $this->formElementErrors($form->get('email')); ?>
				<?php echo $this->formElement($form->get('email')->setAttribute('class' , 'form-control')) ?>
			</div>
			
			</div>
			<div class="row">
				<div class="container">
				<?php
					echo $this->formElement($form->get('submit')
							->setAttributes(array(
								'class' => 'btn btn-lg btn-primary',
								'value' => 'Submit Ticket',
						)));
				?>
				<?php echo $this->form()->closeTag(); ?>
				</div>
			</div>
			</div>
		</div>
	</div>
</div>
