<div class="jumbotron">
	<h2>Welcome to cTicket! (WIP)</h2> 
	Simple Ticket system with reporting capabilities
	Practice in application development in Zend Framework 2.
	<br>
	<a class="btn btn-lg btn-primary" href="<?php echo $this->url('cticket/ticket-admin', array('action' => 'create')) ?>"> Submit Ticket</a>
	<a class="btn btn-lg btn-default" href="<?php echo $this->url('cticket/ticket-admin', array('action' => 'index')) ?>">Open Ticket List</a>
</div>